openapi: 3.0.1
info:
  title: Tornado Tutorial
  version: 0.0.0
paths:
  /urls:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    url:
                      type: string
